nn_architecture: # 4-128-128-2
  - 4
  - 128
  - 128
  - 128
  - 128
  - 2
learning_rate: 0.0001
learning_rate_decay: 0.999
epochs: 500
policy: "epsilon_greedy"
epsilon:
  initial: 0.2
  decay: 0.98
  min: 0.01
temp:
  initial: 0.1
  decay: 0.99
  min: 0.05
gamma: 0.9
target_network_sync_freq: 1
sampling_rate: 16
buffer_size: 10000
