
nn_architecture: # [4, 2] 
  - 4
  - 2
learning_rate: 0.001
learning_rate_decay: 1.0
epochs: 1000
policy: "random"
epsilon:
  initial: 1.0
  decay: 0.99
  min: 0.01
temp:
  initial: 0.1
  decay: 0.99
  min: 0.05
gamma: 0.9
target_network_sync_freq: 1
sampling_rate: 2
buffer_size: 1000000