
nn_architecture: # [4, 128],[128 , 128], [128, 2]
  - 4
  - 128
  - 128
  - 128
  - 128
  - 2
learning_rate: 0.0001
learning_rate_decay: 1.0
epochs: 1000
policy: "epsilon_greedy"
epsilon:
  initial: 0.9
  decay: 0.99
  min: 0.05
temp:
  initial: 0.1
  decay: 0.99
  min: 0.05
gamma: 0.99
sampling_rate: 128
buffer-size: 10000