nn_architecture: # [4, 64], [64, 32], [32, 32], [32, 2]
  - 4
  - 64
  - 64
  - 32
  - 32
  - 32
  - 32
  - 2
learning_rate: 0.001
learning_rate_decay: 1.0
epochs: 1000
policy: "epsilon_greedy"
epsilon:
  initial: 0.2
  decay: 0.99
  min: 0.01
temp:
  initial: 0.1
  decay: 0.99
  min: 0.05
gamma: 0.9
target_network_sync_freq: 1
sampling_rate: 10
buffer_size: 1000000