name: build report pdf

concurrency:
  group: ${{ github.ref }}-docs
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'report/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: report/
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: report/main.pdf